name: build mkdocs and publish

on:
  push:
    branches: 
      - master
    tags:
      - 'release-v**.**.**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build document
        env:
          GITHUB_ACTIONS: true
        run: docker-compose up

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME=`echo ${GITHUB_REF##refs/tags/} | sed -E 's/release-//g'`
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::${TAG_NAME}"

      - name: Deploy to GitHub Pages with tag
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
        with:
          tagName: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tagMessage: "Deployment ${{ steps.prepare_tag.outputs.tag_name }}"
          tagOverwrite: true
          keepFiles: true

      - name: Deploy to GitHub Pages with push master 
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/heads/master')
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
        with:
          keepFiles: true
